#cloud-config
autoinstall:
  version: 1

  identity:
    hostname: SW-Dev
    username: sw
    # SHA-512-crypt of: retym@Work2020 with fixed salt SWDev2020
    password: "$6$SWDev2020$Viu/DM2nzwhvlcO0B6E5pOmrI1rCxE/Rg64A1ChwuiL.8p0GB55eBeNgB8jmjEnw.kvTxk7IqpIxk.m1Nnljc1"

  locale: en_US
  keyboard:
    layout: us

  ssh:
    install-server: true

  packages:
    - net-tools
    - openssh-server
    - gcc
    - mingw-w64
    - gcc-aarch64-linux-gnu

  storage:
    config:
      # Disk (adjust /dev/sda -> /dev/vda or /dev/nvme0n1 if needed)
      - id: disk0
        type: disk
        match: { path: /dev/sda }
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: true

      # --- Partitions (per screenshots) ---
      - id: part-bios
        type: partition
        device: disk0
        size: 4094M
        flag: bios_grub

      - id: part-efi
        type: partition
        device: disk0
        size: 4095M
        # For EFI on GPT, set both flags
        flags: [ boot, esp ]

      - id: part-swap
        type: partition
        device: disk0
        size: 4095M

      - id: part-boot
        type: partition
        device: disk0
        size: 4095M

      - id: part-opt
        type: partition
        device: disk0
        size: 4095M

      - id: part-usr
        type: partition
        device: disk0
        size: 10240M

      - id: part-var
        type: partition
        device: disk0
        size: 10240M

      - id: part-root
        type: partition
        device: disk0
        size: -1   # remainder

      # --- Formats ---
      # (no format for BIOS_GRUB)
      - id: fmt-efi
        type: format
        fstype: vfat
        volume: part-efi

      - id: fmt-swap
        type: format
        fstype: swap
        volume: part-swap

      - id: fmt-boot
        type: format
        fstype: ext4
        volume: part-boot

      - id: fmt-opt
        type: format
        fstype: ext4
        volume: part-opt

      - id: fmt-usr
        type: format
        fstype: ext4
        volume: part-usr

      - id: fmt-var
        type: format
        fstype: ext4
        volume: part-var

      - id: fmt-root
        type: format
        fstype: ext4
        volume: part-root

      # --- Mounts ---
      - { id: mnt-efi,  type: mount, device: fmt-efi,  path: /boot/efi }
      - { id: mnt-boot, type: mount, device: fmt-boot, path: /boot }
      - { id: mnt-opt,  type: mount, device: fmt-opt,  path: /opt }
      - { id: mnt-usr,  type: mount, device: fmt-usr,  path: /usr }
      - { id: mnt-var,  type: mount, device: fmt-var,  path: /var }
      - { id: mnt-root, type: mount, device: fmt-root, path: / }

  late-commands:
    # Ensure sw has sudo and passwordless sudo
    - curtin in-target --target=/target -- usermod -aG sudo sw
    - curtin in-target --target=/target -- /bin/sh -c "printf 'sw ALL=(ALL) NOPASSWD:ALL\n' >/etc/sudoers.d/90-sw && chmod 440 /etc/sudoers.d/90-sw"

    # Enable auto-login (GDM3 if present)
    - |
      curtin in-target --target=/target -- bash -c '
        if [ -d /etc/gdm3 ]; then
          cat >/etc/gdm3/custom.conf <<EOF
[daemon]
AutomaticLoginEnable=true
AutomaticLogin=sw
EOF
        fi
      '
    # Enable auto-login (LightDM flavors)
    - |
      curtin in-target --target=/target -- bash -c '
        if [ -d /etc/lightdm ]; then
          mkdir -p /etc/lightdm/lightdm.conf.d
          cat >/etc/lightdm/lightdm.conf.d/50-autologin.conf <<EOF
[Seat:*]
autologin-user=sw
autologin-user-timeout=0
EOF
        fi
      '
    - curtin in-target --target=/target -- apt-get update

