#cloud-config
autoinstall:
  version: 1

  identity:
    hostname: SW-Dev
    username: sw
    # SHA-512-crypt of: retym@Work2020 with fixed salt SWDev2020 (deterministic)
    password: "$6$SWDev2020$Viu/DM2nzwhvlcO0B6E5pOmrI1rCxE/Rg64A1ChwuiL.8p0GB55eBeNgB8jmjEnw.kvTxk7IqpIxk.m1Nnljc1"

  locale: en_US
  keyboard:
    layout: us

  ssh:
    install-server: true

  packages:
    - net-tools
    - openssh-server
    - gcc
    - mingw-w64
    - gcc-aarch64-linux-gnu

  storage:
    config:
      # Disk (change /dev/sda if needed)
      - id: disk0
        type: disk
        path: /dev/sda
        ptable: gpt
        wipe: superblock-recursive
        preserve: false
        grub_device: true

      # Partitions (UEFI)
      - id: part-efi
        type: partition
        device: disk0
        size: 4096M

      - id: part-swap
        type: partition
        device: disk0
        size: 4096M

      - id: part-boot
        type: partition
        device: disk0
        size: 4096M

      - id: part-opt
        type: partition
        device: disk0
        size: 4096M

      - id: part-usr
        type: partition
        device: disk0
        size: 10240M

      - id: part-var
        type: partition
        device: disk0
        size: 10240M

      - id: part-root
        type: partition
        device: disk0
        size: -1   # remainder

      # Formats
      - id: fmt-efi
        type: format
        fstype: vfat
        volume: part-efi

      - id: fmt-swap
        type: format
        fstype: swap
        volume: part-swap

      - id: fmt-boot
        type: format
        fstype: ext4
        volume: part-boot

      - id: fmt-opt
        type: format
        fstype: ext4
        volume: part-opt

      - id: fmt-usr
        type: format
        fstype: ext4
        volume: part-usr

      - id: fmt-var
        type: format
        fstype: ext4
        volume: part-var

      - id: fmt-root
        type: format
        fstype: ext4
        volume: part-root

      # Mounts
      - { id: mnt-efi,  type: mount, device: fmt-efi,  path: /boot/efi }
      - { id: mnt-boot, type: mount, device: fmt-boot, path: /boot }
      - { id: mnt-opt,  type: mount, device: fmt-opt,  path: /opt }
      - { id: mnt-usr,  type: mount, device: fmt-usr,  path: /usr }
      - { id: mnt-var,  type: mount, device: fmt-var,  path: /var }
      - { id: mnt-root, type: mount, device: fmt-root, path: / }

  late-commands:
    # Ensure sw is in sudo group (usually already is, but explicit is fine)
    - curtin in-target --target=/target -- usermod -aG sudo sw
    # LightDM directory might not exist until the package is present; create it so write_files can drop a config at first boot
    - curtin in-target --target=/target -- mkdir -p /etc/lightdm/lightdm.conf.d || true
    - curtin in-target --target=/target -- apt-get update

# Write config files on the installed system (first boot), avoiding YAML quoting issues
write_files:
  # Passwordless sudo
  - path: /etc/sudoers.d/90-sw
    permissions: "0440"
    content: |
      sw ALL=(ALL) NOPASSWD:ALL

  # GDM3 auto-login (Ubuntu Desktop)
  - path: /etc/gdm3/custom.conf
    permissions: "0644"
    content: |
      [daemon]
      AutomaticLoginEnable=true
      AutomaticLogin=sw

  # LightDM auto-login (flavors using LightDM)
  - path: /etc/lightdm/lightdm.conf.d/50-autologin.conf
    permissions: "0644"
    content: |
      [Seat:*]
      autologin-user=sw
      autologin-user-timeout=0
